wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 64
HIDDEN_DIM:
  desc: null
  value: 256
INNER_DIM:
  desc: null
  value: 512
LEARNING_RATE:
  desc: null
  value: 0.0001
N:
  desc: null
  value: 2
NUM_HEAD:
  desc: null
  value: 8
SEQ_LEN:
  desc: null
  value: 60
VOCAB_SIZE:
  desc: null
  value: 10000
WEIGHT_DECAY:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1661140825.724931
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.9.12
      5: 0.13.1
      8:
      - 1
      - 3
      - 5
